version: '3'

services:
  # Third-party services
  db:
    image: postgres:10.3-alpine
    environment:
      POSTGRES_USER: local
      POSTGRES_PASSWORD: hunter2
      POSTGRES_DB: goresolve
    ports:
      - 5432:5432
  faktory:
    image: contribsys/faktory:0.7.0
    expose:
      - 7419
    ports:
      - 7420:7420
  # metabase:
  #   image: metabase/metabase:v0.28.5
  #   environment:
  #     MB_DB_TYPE: postgres
  #     MB_DB_DBNAME: goresolve
  #     MB_DB_PORT: 5432
  #     MB_DB_USER: local
  #     MB_DB_PASS: hunter2
  #     MB_DB_HOST: db
  #   depends_on:
  #     - db
  #   ports:
  #     - 3000:3000

  # go-resolve services
  goresolve-api:
    build: .
    command: go-resolve-api
    environment:
      FAKTORY_URL: tcp://faktory:7419
      POSTGRES_URL: postgresql://local:hunter2@db:5432/goresolve?sslmode=disable
    depends_on:
      - db
      - faktory
    ports:
      - 80
  goresolve-worker:
    build: .
    command: go-resolve-worker
    environment:
      FAKTORY_URL: tcp://faktory:7419
      POSTGRES_URL: postgresql://local:hunter2@db:5432/goresolve?sslmode=disable
    depends_on:
      - db
      - faktory