[[constraint]]
  name = "github.com/contribsys/faktory"
  version = "0.7.0-1"

[[constraint]]
  branch = "master"
  name = "github.com/contribsys/faktory_worker_go"

[[constraint]]
  name = "github.com/go-chi/chi"
  version = "3.3.2"

[[constraint]]
  branch = "master"
  name = "github.com/ilikebits/go-core"

[[constraint]]
  branch = "master"
  name = "github.com/jmoiron/sqlx"

[[constraint]]
  branch = "master"
  name = "github.com/lib/pq"

[[constraint]]
  name = "github.com/pkg/errors"
  version = "0.8.0"

[[constraint]]
  name = "gopkg.in/src-d/go-git.v4"
  version = "4.4.1"

[prune]
  go-tests = true
  unused-packages = true
